# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: broadcast.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'broadcast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62roadcast.proto\x12\tbroadcast\"+\n\x0cSubscribeReq\x12\x1b\n\x13replay_seq_no_start\x18\x01 \x01(\x03\";\n\x05\x46rame\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x0e\n\x06seq_no\x18\x02 \x01(\r\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2t\n\tBroadcast\x12\x38\n\tSubscribe\x12\x17.broadcast.SubscribeReq\x1a\x10.broadcast.Frame0\x01\x12-\n\x07Publish\x12\x10.broadcast.Frame\x1a\x0e.broadcast.Ack(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'broadcast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQ']._serialized_start=30
  _globals['_SUBSCRIBEREQ']._serialized_end=73
  _globals['_FRAME']._serialized_start=75
  _globals['_FRAME']._serialized_end=134
  _globals['_ACK']._serialized_start=136
  _globals['_ACK']._serialized_end=158
  _globals['_BROADCAST']._serialized_start=160
  _globals['_BROADCAST']._serialized_end=276
# @@protoc_insertion_point(module_scope)
